export const AUTH_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const FLUSH_ERRORS = 'FLUSH_ERRORS';
export const CAKE_SUCCESS = 'CAKE_SUCCESS';
export const CAKE_FAILED = 'CAKE_FAILED';
export const CAKE_LOADING = 'CAKE_LOADING';


